"""initial schema

Revision ID: 07792e6c6425
Revises: 
Create Date: 2026-08-07 10:39:36.495854

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '07792e6c6425'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('defect_categories',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('operators',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pin_code', sa.String(length=6), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=False),
    sa.Column('last_name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pin_code')
    )
    op.create_table('product_models',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('barcode_prefix', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('barcode_prefix')
    )
    op.create_table('production_lines',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('daily_target', sa.Integer(), nullable=False),
    sa.Column('weekly_target', sa.Integer(), nullable=False),
    sa.Column('monthly_target', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('root_causes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=False),
    sa.Column('last_name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('audits',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('production_line_id', sa.Integer(), nullable=False),
    sa.Column('audited_by_user_id', sa.Integer(), nullable=False),
    sa.Column('audit_month', sa.String(length=7), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['audited_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['production_line_id'], ['production_lines.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reports',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('report_type', sa.String(length=50), nullable=False),
    sa.Column('date_range_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('date_range_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('generated_by_user_id', sa.Integer(), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['generated_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tvs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('serial_number', sa.String(length=30), nullable=False),
    sa.Column('line_id', sa.Integer(), nullable=False),
    sa.Column('product_model_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['line_id'], ['production_lines.id'], ),
    sa.ForeignKeyConstraint(['product_model_id'], ['product_models.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('serial_number')
    )
    op.create_table('audit_findings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('audit_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['audit_id'], ['audits.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('defects',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tv_id', sa.Integer(), nullable=False),
    sa.Column('defect_category_id', sa.Integer(), nullable=False),
    sa.Column('root_cause_id', sa.Integer(), nullable=True),
    sa.Column('found_by_operator_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('found_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['defect_category_id'], ['defect_categories.id'], ),
    sa.ForeignKeyConstraint(['found_by_operator_id'], ['operators.id'], ),
    sa.ForeignKeyConstraint(['root_cause_id'], ['root_causes.id'], ),
    sa.ForeignKeyConstraint(['tv_id'], ['tvs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inspections',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tv_id', sa.Integer(), nullable=False),
    sa.Column('inspector_operator_id', sa.Integer(), nullable=False),
    sa.Column('result', sa.String(length=10), nullable=False),
    sa.Column('inspected_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['inspector_operator_id'], ['operators.id'], ),
    sa.ForeignKeyConstraint(['tv_id'], ['tvs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('production_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tv_id', sa.Integer(), nullable=False),
    sa.Column('line_id', sa.Integer(), nullable=False),
    sa.Column('operator_id', sa.Integer(), nullable=False),
    sa.Column('production_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('shift', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['line_id'], ['production_lines.id'], ),
    sa.ForeignKeyConstraint(['operator_id'], ['operators.id'], ),
    sa.ForeignKeyConstraint(['tv_id'], ['tvs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tv_id')
    )
    op.create_table('repairs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('defect_id', sa.Integer(), nullable=False),
    sa.Column('repaired_by_operator_id', sa.Integer(), nullable=False),
    sa.Column('repair_notes', sa.Text(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['defect_id'], ['defects.id'], ),
    sa.ForeignKeyConstraint(['repaired_by_operator_id'], ['operators.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('repairs')
    op.drop_table('production_records')
    op.drop_table('inspections')
    op.drop_table('defects')
    op.drop_table('audit_findings')
    op.drop_table('tvs')
    op.drop_table('reports')
    op.drop_table('audits')
    op.drop_table('users')
    op.drop_table('root_causes')
    op.drop_table('production_lines')
    op.drop_table('product_models')
    op.drop_table('operators')
    op.drop_table('defect_categories')
    # ### end Alembic commands ###
