"""inspection defect_reason ve tv product_model_id nullable

Revision ID: 2e31ece67077
Revises: 07792e6c6425
Create Date: 2026-08-13 09:19:42.251665

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e31ece67077'
down_revision: Union[str, Sequence[str], None] = '07792e6c6425'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inspections', sa.Column('defect_reason', sa.Text(), nullable=True))
    op.alter_column('tvs', 'product_model_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tvs', 'product_model_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('inspections', 'defect_reason')
    # ### end Alembic commands ###
