"""inspection PIN kaldirildi, defect_category_id eklendi

Revision ID: e3da7598dce4
Revises: 2e31ece67077
Create Date: 2026-08-18 14:17:41.435068

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e3da7598dce4'
down_revision: Union[str, Sequence[str], None] = '2e31ece67077'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inspections', sa.Column('defect_category_id', sa.Integer(), nullable=True))
    op.alter_column('inspections', 'inspector_operator_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_foreign_key(None, 'inspections', 'defect_categories', ['defect_category_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'inspections', type_='foreignkey')
    op.alter_column('inspections', 'inspector_operator_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('inspections', 'defect_category_id')
    # ### end Alembic commands ###
