from typing import Protocol
from app.domain.entities.defect_category import DefectCategory


class DefectCategoryRepository(Protocol):
    def list_all(self) -> list[DefectCategory]: ...
    def save(self, category: DefectCategory) -> DefectCategory: ...
    def get_by_id(self, category_id: int) -> DefectCategory | None: ...
